package com.example.project.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val COVID_URL = "covid"
const val GENDER_URL = "gender"
const val HOSPITAL_URL = "hospital"
const val ADDHOSPITAL_URL = "addhospital"
const val KPLC_URL = "kplc"
const val MENTAL_URL = "mental"
const val NATURE_URL = "nature"
const val POLICE_URL = "police"
const val ADMIN_URL = "admin"
const val FIRSTAID_URL = "firstaid"
const val ADDFIRSTAID_URL = "addfirstaid"
const val NOTIFICATIONS_URL = "notifications"
const val SETTINGS_URL = "settings"
const val SPLASH_URL = "splash"
const val PROFILE_URL = "profile"
const val TRAINING_URL = "training"
const val VIDEOS_URL = "videos"
const val DASHBOARD_URL = "dashboard"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val EMERGENCY_URL = "Emergency"
const val ABOUT_URL = "About"
